-- Tabela de alunos para Supabase
CREATE TABLE public.students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number INTEGER UNIQUE NOT NULL,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'CFC',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Tabela de resets diários
CREATE TABLE public.resets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reset_date DATE UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Tabela CFC (referência)
CREATE TABLE public."CFC" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Inserir alunos
INSERT INTO public.students (number, name, status) VALUES
  (1, 'WALLACE', 'CFC'),
  (2, 'GUEDES', 'CFC'),
  (3, 'OLIVEIRA', 'CFC'),
  (4, 'GALVÃO', 'CFC'),
  (5, 'FONSECA', 'CFC'),
  (6, 'CARVALHO', 'CFC'),
  (7, 'CAMARGO', 'CFC'),
  (8, 'RIBEIRO', 'CFC'),
  (9, 'TALLIS', 'CFC'),
  (10, 'LA RUBIA', 'CFC'),
  (11, 'NASCIMENTO', 'CFC'),
  (12, 'LUCAS MACEDO', 'CFC'),
  (13, 'RICK', 'CFC'),
  (14, 'EDUARDO F', 'CFC'),
  (15, 'BRAVIM', 'CFC'),
  (16, 'ADIEL', 'CFC'),
  (17, 'FLORES', 'CFC'),
  (18, 'JORGE', 'CFC'),
  (19, 'GUIMARÃES', 'CFC'),
  (20, 'JAMOCELLI', 'CFC'),
  (21, 'ISRAEL', 'CFC'),
  (22, 'OLIVEIRA', 'CFC'),
  (23, 'MAIA', 'CFC'),
  (24, 'MOURA', 'CFC'),
  (25, 'KEYNER', 'CFC'),
  (26, 'MARCON', 'CFC'),
  (27, 'FRIESEN', 'CFC'),
  (28, 'SILVESTRE', 'CFC'),
  (29, 'SABINO', 'CFC'),
  (30, 'DOLINSKI', 'CFC'),
  (31, 'J. CASTRO', 'CFC'),
  (32, 'FLAUZINO', 'CFC'),
  (33, 'BRITO', 'CFC'),
  (34, 'PICUSSA', 'CFC'),
  (35, 'MIKTIV', 'CFC'),
  (36, 'ALLAN', 'CFC'),
  (37, 'ALVES', 'CFC'),
  (38, 'RIBEIRO', 'CFC'),
  (39, 'FRUTUOSO', 'CFC'),
  (40, 'FAGUNDES', 'CFC')
ON CONFLICT (number) DO NOTHING;

-- Row Level Security (opcional, para produção)
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."CFC" ENABLE ROW LEVEL SECURITY;

-- Políticas para permitir leitura pública (sem autenticação)
CREATE POLICY "Enable read access for all users" ON public.students
  FOR SELECT USING (true);

CREATE POLICY "Enable update for all users" ON public.students
  FOR UPDATE USING (true) WITH CHECK (true);

CREATE POLICY "Enable read access for resets" ON public.resets
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for resets" ON public.resets
  FOR INSERT WITH CHECK (true);
