const { sql } = require('@vercel/postgres')

const studentList = [
  { numero: 1, nome: 'WALLACE' },
  { numero: 2, nome: 'GUEDES' },
  { numero: 3, nome: 'OLIVEIRA' },
  { numero: 4, nome: 'GALVÃO' },
  { numero: 5, nome: 'FONSECA' },
  { numero: 6, nome: 'CARVALHO' },
  { numero: 7, nome: 'CAMARGO' },
  { numero: 8, nome: 'RIBEIRO' },
  { numero: 9, nome: 'TALLIS' },
  { numero: 10, nome: 'LA RUBIA' },
  { numero: 11, nome: 'NASCIMENTO' },
  { numero: 12, nome: 'LUCAS MACEDO' },
  { numero: 13, nome: 'RICK' },
  { numero: 14, nome: 'EDUARDO F' },
  { numero: 15, nome: 'BRAVIM' },
  { numero: 16, nome: 'ADIEL' },
  { numero: 17, nome: 'FLORES' },
  { numero: 18, nome: 'JORGE' },
  { numero: 19, nome: 'GUIMARÃES' },
  { numero: 20, nome: 'JAMOCELLI' },
  { numero: 21, nome: 'ISRAEL' },
  { numero: 22, nome: 'OLIVEIRA' },
  { numero: 23, nome: 'MAIA' },
  { numero: 24, nome: 'MOURA' },
  { numero: 25, nome: 'KEYNER' },
  { numero: 26, nome: 'MARCON' },
  { numero: 27, nome: 'FRIESEN' },
  { numero: 28, nome: 'SILVESTRE' },
  { numero: 29, nome: 'SABINO' },
  { numero: 30, nome: 'DOLINSKI' },
  { numero: 31, nome: 'J. CASTRO' },
  { numero: 32, nome: 'FLAUZINO' },
  { numero: 33, nome: 'BRITO' },
  { numero: 34, nome: 'PICUSSA' },
  { numero: 35, nome: 'MIKTIV' },
  { numero: 36, nome: 'ALLAN' },
  { numero: 37, nome: 'ALVES' },
  { numero: 38, nome: 'RIBEIRO' },
  { numero: 39, nome: 'FRUTUOSO' },
  { numero: 40, nome: 'FAGUNDES' }
]

async function ensureSchema() {
  await sql`
    CREATE TABLE IF NOT EXISTS students (
      id SERIAL PRIMARY KEY,
      numero INTEGER UNIQUE NOT NULL,
      nome TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'CFC'
    );
  `

  await sql`
    CREATE TABLE IF NOT EXISTS resets (
      id SERIAL PRIMARY KEY,
      reset_date DATE UNIQUE NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
    );
  `

  await sql`
    CREATE TABLE IF NOT EXISTS "CFC" (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
    );
  `

  const existing = await sql`SELECT count(*) as count FROM students;`
  const currentCount = Number(existing.rows[0].count)

  if (currentCount === 0) {
    for (const student of studentList) {
      await sql`
        INSERT INTO students (numero, nome, status)
        VALUES (${student.numero}, ${student.nome}, 'CFC')
        ON CONFLICT (numero) DO NOTHING;
      `
    }
  }
}

async function applyDailyReset() {
  const today = new Date().toISOString().slice(0, 10)
  const result = await sql`
    SELECT 1 FROM resets WHERE reset_date = ${today} LIMIT 1;
  `

  if (result.rowCount === 0) {
    await sql`
      UPDATE students SET status = 'CFC';
    `
    await sql`
      INSERT INTO resets (reset_date) VALUES (${today});
    `
  }
}

function parseJsonBody(request) {
  return new Promise((resolve, reject) => {
    let body = ''
    request.on('data', (chunk) => {
      body += chunk
    })
    request.on('end', () => {
      try {
        resolve(body ? JSON.parse(body) : {})
      } catch (error) {
        reject(error)
      }
    })
    request.on('error', reject)
  })
}

async function handler(request, response) {
  const method = request.method

  try {
    await ensureSchema()
    await applyDailyReset()

    if (method === 'GET') {
      const students = await sql`SELECT id, numero, nome, status FROM students ORDER BY numero ASC;`
      response.statusCode = 200
      response.setHeader('Content-Type', 'application/json')
      response.end(JSON.stringify({ students: students.rows }))
      return
    }

    if (method === 'PATCH') {
      const body = await parseJsonBody(request)
      const { id, status } = body

      if (!id || !status) {
        response.statusCode = 400
        response.setHeader('Content-Type', 'application/json')
        response.end(JSON.stringify({ error: 'Invalid body' }))
        return
      }

      await sql`
        UPDATE students SET status = ${status} WHERE id = ${id};
      `

      const students = await sql`SELECT id, numero, nome, status FROM students ORDER BY numero ASC;`
      response.statusCode = 200
      response.setHeader('Content-Type', 'application/json')
      response.end(JSON.stringify({ students: students.rows }))
      return
    }

    response.statusCode = 405
    response.setHeader('Content-Type', 'application/json')
    response.end(JSON.stringify({ error: 'Method not allowed' }))
  } catch (error) {
    response.statusCode = 500
    response.setHeader('Content-Type', 'application/json')
    response.end(JSON.stringify({ error: 'Database error', details: error.message }))
  }
}

module.exports = handler
