const { sql } = require('@vercel/postgres')

const studentList = [
  { number: 1, name: 'WALLACE' },
  { number: 2, name: 'GUEDES' },
  { number: 3, name: 'OLIVEIRA' },
  { number: 4, name: 'GALVÃO' },
  { number: 5, name: 'FONSECA' },
  { number: 6, name: 'CARVALHO' },
  { number: 7, name: 'CAMARGO' },
  { number: 8, name: 'RIBEIRO' },
  { number: 9, name: 'TALLIS' },
  { number: 10, name: 'LA RUBIA' },
  { number: 11, name: 'NASCIMENTO' },
  { number: 12, name: 'LUCAS MACEDO' },
  { number: 13, name: 'RICK' },
  { number: 14, name: 'EDUARDO F' },
  { number: 15, name: 'BRAVIM' },
  { number: 16, name: 'ADIEL' },
  { number: 17, name: 'FLORES' },
  { number: 18, name: 'JORGE' },
  { number: 19, name: 'GUIMARÃES' },
  { number: 20, name: 'JAMOCELLI' },
  { number: 21, name: 'ISRAEL' },
  { number: 22, name: 'OLIVEIRA' },
  { number: 23, name: 'MAIA' },
  { number: 24, name: 'MOURA' },
  { number: 25, name: 'KEYNER' },
  { number: 26, name: 'MARCON' },
  { number: 27, name: 'FRIESEN' },
  { number: 28, name: 'SILVESTRE' },
  { number: 29, name: 'SABINO' },
  { number: 30, name: 'DOLINSKI' },
  { number: 31, name: 'J. CASTRO' },
  { number: 32, name: 'FLAUZINO' },
  { number: 33, name: 'BRITO' },
  { number: 34, name: 'PICUSSA' },
  { number: 35, name: 'MIKTIV' },
  { number: 36, name: 'ALLAN' },
  { number: 37, name: 'ALVES' },
  { number: 38, name: 'RIBEIRO' },
  { number: 39, name: 'FRUTUOSO' },
  { number: 40, name: 'FAGUNDES' }
]

async function ensureSchema() {
  await sql`
    CREATE TABLE IF NOT EXISTS students (
      id SERIAL PRIMARY KEY,
      number INTEGER UNIQUE NOT NULL,
      name TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'CFC'
    );
  `

  await sql`
    CREATE TABLE IF NOT EXISTS resets (
      id SERIAL PRIMARY KEY,
      reset_date DATE UNIQUE NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
    );
  `

  await sql`
    CREATE TABLE IF NOT EXISTS "CFC" (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
    );
  `

  const existing = await sql`SELECT count(*) as count FROM students;`
  const currentCount = Number(existing.rows[0].count)

  if (currentCount === 0) {
    for (const student of studentList) {
      await sql`
        INSERT INTO students (number, name, status)
        VALUES (${student.number}, ${student.name}, 'CFC')
        ON CONFLICT (number) DO NOTHING;
      `
    }
  }
}

async function applyDailyReset() {
  const today = new Date().toISOString().slice(0, 10)
  const result = await sql`
    SELECT 1 FROM resets WHERE reset_date = ${today} LIMIT 1;
  `

  if (result.rowCount === 0) {
    await sql`
      UPDATE students SET status = 'CFC';
    `
    await sql`
      INSERT INTO resets (reset_date) VALUES (${today});
    `
  }
}

function parseJsonBody(request) {
  return new Promise((resolve, reject) => {
    let body = ''
    request.on('data', (chunk) => {
      body += chunk
    })
    request.on('end', () => {
      try {
        resolve(body ? JSON.parse(body) : {})
      } catch (error) {
        reject(error)
      }
    })
    request.on('error', reject)
  })
}

async function handler(request, response) {
  const method = request.method

  try {
    await ensureSchema()
    await applyDailyReset()

    if (method === 'GET') {
      const students = await sql`SELECT id, number, name, status FROM students ORDER BY number ASC;`
      response.statusCode = 200
      response.setHeader('Content-Type', 'application/json')
      response.end(JSON.stringify({ students: students.rows }))
      return
    }

    if (method === 'PATCH') {
      const body = await parseJsonBody(request)
      const { id, status } = body

      if (!id || !status) {
        response.statusCode = 400
        response.setHeader('Content-Type', 'application/json')
        response.end(JSON.stringify({ error: 'Invalid body' }))
        return
      }

      await sql`
        UPDATE students SET status = ${status} WHERE id = ${id};
      `

      const students = await sql`SELECT id, number, name, status FROM students ORDER BY number ASC;`
      response.statusCode = 200
      response.setHeader('Content-Type', 'application/json')
      response.end(JSON.stringify({ students: students.rows }))
      return
    }

    response.statusCode = 405
    response.setHeader('Content-Type', 'application/json')
    response.end(JSON.stringify({ error: 'Method not allowed' }))
  } catch (error) {
    response.statusCode = 500
    response.setHeader('Content-Type', 'application/json')
    response.end(JSON.stringify({ error: 'Database error', details: error.message }))
  }
}

module.exports = handler
